/**
 * KROWN ERP - Offline Sync Engine (SaaS Version)
 *
 * Stores explicitly retryable write operations in IndexedDB when offline.
 * Replays them only through authenticated API endpoints when back online.
 *
 * Security rules:
 * - Never queue authentication/authorization/validation failures.
 * - Never silently retry 4xx business/security failures.
 * - Queue only when the browser is actually offline or the server reports a
 *   transient condition (408/429/5xx).
 * - Orders should carry an idempotency key generated by the order client so a
 *   retry cannot create a second order.
 */

import { openDB, IDBPDatabase } from 'idb';

const DB_NAME = 'KrownPOS_OfflineDB';
const DB_VERSION = 3;
const QUEUE_STORE = 'op_queue';

export interface OfflineOp {
  id?: number;
  endpoint: string;
  method: string;
  body: any;
  timestamp: number;
  retries: number;
}

let _db: IDBPDatabase | null = null;

export async function getDB(): Promise<IDBPDatabase> {
  if (_db) return _db;
  _db = await openDB(DB_NAME, DB_VERSION, {
    upgrade(db) {
      if (!db.objectStoreNames.contains(QUEUE_STORE)) {
        db.createObjectStore(QUEUE_STORE, { keyPath: 'id', autoIncrement: true });
      }
    },
  });
  return _db;
}

/** Queue a write only when it is genuinely offline. */
export async function queueOfflineOp(op: { endpoint: string; method: string; body: any }) {
  try {
    const db = await getDB();
    await db.add(QUEUE_STORE, {
      ...op,
      timestamp: Date.now(),
      retries: 0,
    } as OfflineOp);
    notifySyncListeners();

    if (typeof navigator !== 'undefined' && navigator.onLine) {
      setTimeout(() => {
        syncOfflineQueue().catch(() => undefined);
      }, 150);
    }
  } catch {
    // Offline persistence must never crash the POS.
  }
}

export async function getPendingOpCount(): Promise<number> {
  try {
    const db = await getDB();
    return await db.count(QUEUE_STORE);
  } catch {
    return 0;
  }
}

function isTransientHttpStatus(status: number): boolean {
  return status === 408 || status === 429 || status >= 500;
}

/** Replay queued operations. Security/validation failures are discarded, not retried. */
export async function syncOfflineQueue(): Promise<{ synced: number; failed: number }> {
  if (typeof navigator !== 'undefined' && !navigator.onLine) {
    return { synced: 0, failed: 0 };
  }

  const db = await getDB();
  const ops: OfflineOp[] = await db.getAll(QUEUE_STORE);
  if (ops.length === 0) return { synced: 0, failed: 0 };

  let synced = 0;
  let failed = 0;

  for (const op of ops) {
    try {
      const token = typeof window !== 'undefined'
        ? localStorage.getItem('krown_session_token') || ''
        : '';
      const headers: Record<string, string> = { 'Content-Type': 'application/json' };
      if (token) headers.Authorization = `Bearer ${token}`;

      const res = await fetch(op.endpoint, {
        method: op.method,
        headers,
        credentials: 'include',
        body: JSON.stringify(op.body),
      });

      if (res.ok) {
        await db.delete(QUEUE_STORE, op.id!);
        synced++;
        continue;
      }

      // Authentication, authorization, validation, conflicts and not-found
      // responses must NEVER be replayed repeatedly. They require a new user
      // action or an explicit recovery flow.
      if (!isTransientHttpStatus(res.status)) {
        await db.delete(QUEUE_STORE, op.id!);
        failed++;
        continue;
      }

      const newRetries = (op.retries || 0) + 1;
      if (newRetries >= 5) {
        await db.delete(QUEUE_STORE, op.id!);
      } else {
        await db.put(QUEUE_STORE, { ...op, retries: newRetries });
      }
      failed++;
    } catch {
      // Network failures remain queued. Do not consume a retry for a transport
      // error; the browser may still be transitioning between networks.
      failed++;
    }
  }

  notifySyncListeners();
  return { synced, failed };
}

export async function clearAllPendingOps(): Promise<void> {
  try {
    const db = await getDB();
    await db.clear(QUEUE_STORE);
    notifySyncListeners();
  } catch {
    // Best effort only.
  }
}

export const forceSyncNow = syncOfflineQueue;

type SyncListener = (pendingCount: number) => void;
const syncListeners = new Set<SyncListener>();

export function onSyncStatusChange(fn: SyncListener) {
  syncListeners.add(fn);
  return () => syncListeners.delete(fn);
}

async function notifySyncListeners() {
  const count = await getPendingOpCount();
  syncListeners.forEach(fn => fn(count));
}

let autoSyncInitialized = false;

export function initAutoSync() {
  if (autoSyncInitialized || typeof window === 'undefined') return;
  autoSyncInitialized = true;

  (async () => {
    try {
      const db = await getDB();
      const ops: OfflineOp[] = await db.getAll(QUEUE_STORE);
      // Old queues can contain operations created by a previous auth state.
      // Do not delete them merely because they are old; replay logic will
      // discard authorization failures safely. Only abandon very stale queues
      // after seven days to prevent unbounded growth.
      const cutoff = Date.now() - 7 * 24 * 60 * 60 * 1000;
      for (const op of ops) {
        if (op.timestamp < cutoff) await db.delete(QUEUE_STORE, op.id!);
      }
    } catch {
      // Ignore offline storage initialization failures.
    }
  })();

  const handleOnline = async () => {
    await syncOfflineQueue().catch(() => undefined);
  };

  window.addEventListener('online', handleOnline);

  if (navigator.onLine) {
    setTimeout(() => {
      syncOfflineQueue().catch(() => undefined);
    }, 3000);
  }
}
